import Head from 'next/head'
import { Input, Row, Col, Pagination } from 'antd';
import "../styles/home.less"
import Axios from 'axios'
import { useState } from 'react';
import Link from 'next/link'
import AnimeCard from '../components/animeCard';

const { Search } = Input

export default function Home () {
  const [animes, setAnimes] = useState([])
  const [query, setQuery] = useState('')
  const [totalProducts, setTotalProducts] = useState(0)
  const [noResults, setNoResults] = useState(false)

  async function fetchNewPage (currentPage) {
    try {
      const { data } = await Axios.get(`https://kitsu.io/api/edge/anime?filter[text]=${query}&page[limit]=8&page[offset]=${currentPage}`) || {}
      setAnimes(data.data)
    } catch (error) {
      console.log(error)
    }
  }

  async function fetchAnimeApi (value) {
    try {
      setQuery(value)
      const { data } = await Axios.get(`https://kitsu.io/api/edge/anime?filter[text]=${value}&page[limit]=8`) || {}

      if (data.data.length) {
        setAnimes(data.data)
        setTotalProducts(data.meta.count)
        setNoResults(false)
      } else {
        setNoResults(true)
      }
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="home-container">
          <div className="input-container">
            <Row>
              <Col span={24}>
                <Search 
                  className="input"
                  placeholder="Busque animes"
                  enterButton
                  onSearch={fetchAnimeApi}
                />
              </Col>
            </Row>
          </div>
          <Row gutter={32}>
            {
              noResults ? <div className="no-results">No results</div> : null
            }
            {animes.map(anime => (
              <Col 
                key={anime.id}
                xl={6}
                lg={6}
                md={8}
                sm={16}
                xs={24}
              >
                <Link 
                  
                  href={`/anime/${anime.id}`}
                >
                  <a>
                    <AnimeCard anime={anime} />
                  </a>
                </Link>
              </Col>
            ))}
          </Row>
        </div>

        {
          totalProducts ? (
            <Pagination 
              defaultCurrent={1}
              total={totalProducts}
              showQuickJumper={false}
              showSizeChanger={false}
              onChange={fetchNewPage}
              defaultPageSize={8}
            />
          ) : null
        }
      </main>
    </div>
  )
}
